import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const classes: string[] = [inter.className, "h-full"]
  return (
    <html lang="en" className='h-full'>
      <body className={classes.join(" ")} >{children}</body>
    </html>
  )
}
